version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: hub_db_dev
    environment:
      POSTGRES_DB: hub_db
      POSTGRES_USER: hub_user
      POSTGRES_PASSWORD: hub_pass
    ports:
      - "5432:5432"
    volumes:
      - hub_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U hub_user -d hub_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  hub_pg_data:
